server:
  port: 13801

spring:
  application:
    name: config-server
  profiles:
    active: native #\u52A0\u8F7D\u672C\u5730\u914D\u7F6E
  cloud:
    config:
      server:
        native:
          #\u4E0D\u6307\u5B9A\u8DEF\u5F84\u7684\u8BDD\uFF0C\u9ED8\u8BA4\u641C\u7D22resources\u76EE\u5F55
          search-locations: H:/SpringCloud/springcloud-config-server/config/

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
