server:
  port: 13801

spring:
  application:
    name: config-server
#  profiles:
#    active: native #\u52A0\u8F7D\u672C\u5730\u914D\u7F6E
  cloud:
    config:
      server:
#        native:
#          #\u4E0D\u6307\u5B9A\u8DEF\u5F84\u7684\u8BDD\uFF0C\u9ED8\u8BA4\u641C\u7D22resources\u76EE\u5F55
#          search-locations: H:/SpringCloud/springcloud-config-server/config/
        git:
          #\u914D\u7F6Egit\u4ED3\u5E93\u7684\u5730\u5740
          uri: https://github.com/fanrendale/SpringCloudConfigServer/
          #git\u4ED3\u5E93\u5730\u5740\u4E0B\u7684\u76F8\u5BF9\u5730\u5740\uFF0C\u53EF\u4EE5\u914D\u7F6E\u591A\u4E2A\uFF0C\u7528","\u5206\u5272
          search-paths: config
          #git\u4ED3\u5E93\u7684\u8D26\u53F7
          username: fanrendale
          #git\u4ED3\u5E93\u7684\u5BC6\u7801
          password: 520xujiafei

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
