
server:
  port: 52601

spring:
  application:
    name: config-client

eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 15
    lease-expiration-duration-in-seconds: 45
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

# 配置客户端输出演示用
info: local-config-client-dev